version: '3.8' 

services: 
  web: 
    build: . 
    ports: 
      - "7755:7755" 
    volumes: 
      - .:/app
    environment: 
      FLASK_APP: core/server.py
    command: bash run.sh

      
  test: 
    build: . 
    environment: 
      FLASK_APP: core/server.py
    command: pytest -vvv -s tests/ 
    volumes: 
      - .:/app